### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sparse'

### ISSUE THREAD

**Issue by parhamgg** [drrelyea/SPGL1_python_port#13]
This error is related to the NormL12 project function in spgl_aux.py
there is nothing named 'sparse' in numpy (np.sparse.spdiags returns this error), we have something in scipy but I'm not sure if you meant to use that. Please fix this as my work depends on it!

**Comment by Jwink3101** [comment]
First, I suspect it is supposed to be `scipy.sparse.spdiags` but I am not sure. Actually, since it is just the diags, you could probably replace it with `np.diag` with a cost to memory.

But, the best thing you can do is provide a [minimal, complete, verifiable, and verifiable example](https://stackoverflow.com/help/mcve) so I can play with it and maybe fix it. 

I have no idea if @drrelyea is still active as (s)he hasn't looked at my pull request, but I may start maintaining my own fork (and doing some **much** needed cleanup) so I can try to fix this.

Also, this whole thing can use some testing to find these types of issues.

**Comment by drrelyea** [comment]
Definitely supposed to be scipy.

I did this on a lark several years ago when my python was a lot weaker and committed it a few years later. You're right that it needs serious cleanup, and I haven't used it in ~6 years. If people are relying on it, then a fork makes sense (and I can edit the README to point at it), because I don't have time to test things. I'm also happy to look over PRs a lot more rapidly if you'd prefer to keep the repo here.
